import type { PositionBoard } from "./constants";

export const TEST_WHITE_POSITION: PositionBoard = [
	{
		color: 'white',
		piece: 'king',
		x: 5,
		y: 5,
		isCaptured: false,
		row: '1',
		col: 'e',
		id: '1e',
		pins: {
			topVertical: false,
			bottomVertical: false,
			leftHorizontal: false,
			rightHorizontal: false,
			LTDiagonal: false,
			LBDiagonal: false,
			RTDiagonal: false,
			RBDiagonal: false,
		},
		legalMoves: [],
	},
	{
		color: 'white',
		piece: 'queen',
		x: 6,
		y: 4,
		isCaptured: false,
		row: '1',
		col: 'c',
		id: '1c',
		pins: {
			topVertical: true,
			bottomVertical: true,
			leftHorizontal: true,
			rightHorizontal: true,
			LTDiagonal: true,
			LBDiagonal: true,
			RTDiagonal: true,
			RBDiagonal: true,
		},
		legalMoves: [],
	},
	{
		color: 'white',
		piece: 'queen',
		x: 5,
		y: 4,
		isCaptured: false,
		row: '1',
		col: 'd',
		id: '1d',
		pins: {
			topVertical: true,
			bottomVertical: true,
			leftHorizontal: true,
			rightHorizontal: true,
			LTDiagonal: true,
			LBDiagonal: true,
			RTDiagonal: true,
			RBDiagonal: true,
		},
		legalMoves: [],
	},
	{
		color: 'white',
		piece: 'queen',
		x: 4,
		y: 4,
		isCaptured: false,
		row: '1',
		col: 'f',
		id: '1f',
		pins: {
			topVertical: true,
			bottomVertical: true,
			leftHorizontal: true,
			rightHorizontal: true,
			LTDiagonal: true,
			LBDiagonal: true,
			RTDiagonal: true,
			RBDiagonal: true,
		},
		legalMoves: [],
	},
	{
		color: 'black',
		piece: 'queen',
		x: 8,
		y: 2,
		isCaptured: false,
		row: '8',
		col: 'd',
		id: '8d',
		pins: {
			topVertical: false,
			bottomVertical: false,
			leftHorizontal: false,
			rightHorizontal: false,
			LTDiagonal: false,
			LBDiagonal: false,
			RTDiagonal: false,
			RBDiagonal: false,
		},
		legalMoves: [],
	},
	{
		color: 'black',
		piece: 'rook',
		x: 5,
		y: 1,
		isCaptured: false,
		row: '8',
		col: 'a',
		id: '8a',
		pins: {
			topVertical: false,
			bottomVertical: false,
			leftHorizontal: false,
			rightHorizontal: false,
			LTDiagonal: false,
			LBDiagonal: false,
			RTDiagonal: false,
			RBDiagonal: false,
		},
		legalMoves: [],
	},
	{
		color: 'black',
		piece: 'bishop',
		x: 2,
		y: 2,
		isCaptured: false,
		row: '8',
		col: 'c',
		id: '8c',
		pins: {
			topVertical: false,
			bottomVertical: false,
			leftHorizontal: false,
			rightHorizontal: false,
			LTDiagonal: false,
			LBDiagonal: false,
			RTDiagonal: false,
			RBDiagonal: false,
		},
		legalMoves: [],
	},
];

export const TEST_BLACK_POSITION: PositionBoard = [
	{
		color: 'black',
		piece: 'king',
		x: 5,
		y: 5,
		isCaptured: false,
		row: '1',
		col: 'e',
		id: '1e',
		pins: {
			topVertical: false,
			bottomVertical: false,
			leftHorizontal: false,
			rightHorizontal: false,
			LTDiagonal: false,
			LBDiagonal: false,
			RTDiagonal: false,
			RBDiagonal: false,
		},
		legalMoves: [],
	},
	{
		color: 'black',
		piece: 'queen',
		x: 4,
		y: 6,
		isCaptured: false,
		row: '1',
		col: 'c',
		id: '1c',
		pins: {
			topVertical: false,
			bottomVertical: false,
			leftHorizontal: false,
			rightHorizontal: false,
			LTDiagonal: false,
			LBDiagonal: false,
			RTDiagonal: false,
			RBDiagonal: false,
		},
		legalMoves: [],
	},
	{
		color: 'black',
		piece: 'queen',
		x: 5,
		y: 6,
		isCaptured: false,
		row: '1',
		col: 'd',
		id: '1d',
		pins: {
			topVertical: false,
			bottomVertical: false,
			leftHorizontal: false,
			rightHorizontal: false,
			LTDiagonal: false,
			LBDiagonal: false,
			RTDiagonal: false,
			RBDiagonal: false,
		},
		legalMoves: [],
	},
	{
		color: 'black',
		piece: 'queen',
		x: 6,
		y: 6,
		isCaptured: false,
		row: '1',
		col: 'f',
		id: '1f',
		pins: {
			topVertical: false,
			bottomVertical: false,
			leftHorizontal: false,
			rightHorizontal: false,
			LTDiagonal: false,
			LBDiagonal: false,
			RTDiagonal: false,
			RBDiagonal: false,
		},
		legalMoves: [],
	},
	{
		color: 'white',
		piece: 'queen',
		x: 2,
		y: 8,
		isCaptured: false,
		row: '8',
		col: 'd',
		id: '8d',
		pins: {
			topVertical: false,
			bottomVertical: false,
			leftHorizontal: false,
			rightHorizontal: false,
			LTDiagonal: false,
			LBDiagonal: false,
			RTDiagonal: false,
			RBDiagonal: false,
		},
		legalMoves: [],
	},
	{
		color: 'white',
		piece: 'rook',
		x: 5,
		y: 8,
		isCaptured: false,
		row: '8',
		col: 'a',
		id: '8a',
		pins: {
			topVertical: false,
			bottomVertical: false,
			leftHorizontal: false,
			rightHorizontal: false,
			LTDiagonal: false,
			LBDiagonal: false,
			RTDiagonal: false,
			RBDiagonal: false,
		},
		legalMoves: [],
	},
	{
		color: 'white',
		piece: 'bishop',
		x: 8,
		y: 8,
		isCaptured: false,
		row: '8',
		col: 'c',
		id: '8c',
		pins: {
			topVertical: false,
			bottomVertical: false,
			leftHorizontal: false,
			rightHorizontal: false,
			LTDiagonal: false,
			LBDiagonal: false,
			RTDiagonal: false,
			RBDiagonal: false,
		},
		legalMoves: [],
	},
];